services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: yoo_development
      POSTGRES_USER: yoo
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U yoo -d yoo_development"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    init: true
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - type: bind
        source: .
        target: /root/yoo
    ports:
      - "3000:3000"
    environment:
      - RAILS_ENV=development
      - DATABASE_URL=postgresql://yoo:password@db:5432/yoo_development
      - DATABASE_TEST_URL=postgresql://yoo:password@db:5432/yoo_test
    stdin_open: true
    tty: true

volumes:
  postgres_data: